# Production Generation Configuration
# High-quality music generation with constrained sampling

generation:
  # Basic parameters
  max_length: 100
  min_length: 50
  temperature: 0.8
  
  # Sampling strategy and constraints
  use_constrained_sampling: true
  min_notes: 5
  target_notes: 100
  
  # Quality settings
  enforce_note_pairing: true
  prevent_early_end: true
  musical_structure_bias: true
  
  # Advanced parameters
  repetition_penalty: 1.2
  note_completion_bias: 2.0
  velocity_variety: true

# Export settings
export:
  format: "midi"
  include_metadata: true
  title_prefix: "Aurl Production"
  tempo: 120
  
# Output organization
output:
  base_dir: "outputs/production"
  include_timestamp: true
  include_metrics: true
  generate_reports: true